default_context:
  project_name: 'Tegelio'
  project_slug: 'tegelio'
  domain_main: 'tegelio.com'
  domain_staging: 'stag.tegelio.com'
  docker_swarm_stack_name_main: 'tegelio-com'
  docker_swarm_stack_name_staging: 'stag-tegelio-com'
  secret_key: 'ac0205ed1ec53038562bbf17eeb7c582b2b0859adc8d5ab748930e6db82f295f'
  first_superuser: 'erik.lucas.smit@gmail.com'
  first_superuser_password: 'f716139f9b4b804d253c6da2a3e765abf71da678081784bc04bd051be39663be'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.tegelio.com", "https://stag.tegelio.com", "https://tegelio.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@tegelio.com'
  postgres_password: 'e487188393686b6435b22bdab26f8200b0bf9e8b878ada898eb4f8fb5ef50d1f'
  pgadmin_default_user: 'erik.lucas.smit@gmail.com'
  pgadmin_default_user_password: 'f716139f9b4b804d253c6da2a3e765abf71da678081784bc04bd051be39663be'
  traefik_constraint_tag: 'tegelio.com'
  traefik_constraint_tag_staging: 'stag.tegelio.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:f716139f9b4b804d253c6da2a3e765abf71da678081784bc04bd051be39663be'
  sentry_dsn: ''
  docker_image_prefix: 'tegelio'
  docker_image_backend: 'tegelio_backend'
  docker_image_celeryworker: 'tegelio_celeryworker'
  docker_image_frontend: 'tegelio_frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
